# Машинное обучение, АБД

## НИУ ВШЭ, 2025-26 учебный год

# Домашнее задание 2. Часть 1. Классификация новостных данных

Задание выполнил(а):

Мумджи Эмиль

## Общая информация

__Внимание!__  

* Домашнее задание выполняется самостоятельно
* Не допускается помощь в решении домашнего задания от однокурсников или третьих лиц. «Похожие» решения считаются плагиатом, и все задействованные студенты — в том числе и те, у кого списали, — не могут получить за него больше 0 баллов
* Использование в решении домашнего задания генеративных моделей (ChatGPT и так далее) за рамками справочной и образовательной информации для генерации кода задания — считается плагиатом, и такое домашнее задание оценивается в 0 баллов

## Описание задачи

Это домашнее задание посвящено:
* парсингу данных
* навыкам работы с данными
* решению задачи классификации

Формат оценивания:
* Задание проходит в формате [соревнования на Kaggle](https://www.kaggle.com/t/4a5c32474d7d425eae394b6f90e10500)
* Максимальный балл за основные задания: 10
* За хорошие результаты на kaggle (смотри описание ниже) баллы добавляются (без ограничения на 10)

## **Постановка задачи**:
В этом задании вам необходимо построить модель для решения задачи классификации новостных текстов по их тематике. В процессе выполнения вы потренируетесь работать с текстовыми данными, отбирать признаки и, конечно, пройдете практически полный цикл разработки модели (за исключением деплоя).

Успехов!


### **Требования к выполнению задания:**

#### 1. **Сбор данных (4 балла)**

**В рамках выполнения задания вам необходимо:**
   - Спарсить данные из открытых источников (РИА Новости, Лента или другие источники)

Требование:
   - Объем собранных данных: не менее **20000 статей**, распределенных по  тематикам.
   - Новости должны быть свежими — не ранее 2023 года.
  

Для старта вам поможет [ноутбук](https://colab.research.google.com/drive/1b3UkOi7afqX-9uV4raI2YLVkdfmj1dXa) с парсингом Ленты и бейзлайн-решением!



#### 2. **Предобработка данных (2.5 балла)**

**В рамках выполнения задания вам необходимо:**
   - Очистить данные от "мусорных" примеров:
     - Дубликаты
     - Пустые или слишком короткие тексты
     - Другие проблемы
   - Провести токенизацию; по необходимости/желанию: удаление стоп-слов, приведение слов к нормальной форме (лемматизация/стемминг)
   - Подготовить данные для использования в моделях машинного обучения (например, преобразовать тексты в векторы с помощью `TF-IDF`, `CountVectorizer` или другого метода **(выбирая метод, обязательно опишите его)**).

#### 3. **Обучение моделей и анализ результатов (2.5 балла)**

**В рамках выполнения задания вам необходимо:**
   - Построить и сравнить результаты моделей по метрике **accuracy**:
     - Логистическая регрессия
     - Любая другая модель машинного обучения — на ваш выбор
   - Для моделей подобрать гиперпараметры
   - Добиться улучшения качества относительно бейзлайна
   - Сделать прогноз на данных соревнования

#### 4. **Документация и отчет (1 балл)**

**В качестве отчетности вам нужно:**

   - Предоставить два ноутбука:
     - **Ноутбук 1 должен содержать:**
       - Процесс парсинга данных
       - Код для очистки и валидации собранных данных
       - Анализ собранного датасета: распределение по тематикам, примеры текстов
       
     - **Ноутбук 2 должен содержать:**
       - Описание этапов предобработки текста
       - Код для обучения моделей и их сравнения
       - Анализ результатов

   - Сделать итоговый вывод: какая модель показала лучший результат. Выдвинуть гипотезу — почему.

**Этапы работы должны быть подкреплены выводами!**

#### 5. **Топ на kaggle**

*  Если вы попали в топ 20% на private leaderboard, то получите дополнительно **+1 балл** к оценке (сверх максимальных 10)
*  Если вы попали в топ-3 участника - **+2 балла**.



### **Рекомендации:**
- Используйте библиотеку `beautifulsoup4` или `scrapy` для парсинга данных.
- Для работы с текстами используйте библиотеки: `nltk`, `sklearn`.
- Обязательно документируйте все этапы работы.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_pickle('lenta_news.pkl')

In [ ]:
df.shape

(138805, 18)

In [ ]:
df

,docid,url,title,modified,lastmodtime,type,domain,status,part,bloc,tags,image_url,pubdate,text,rightcol,snippet,topic,text_length
0,1552651,https://lenta.ru/news/2024/01/09/politicheski-...,«Политически уже умер» На Украине высказались ...,1704758160,1704782282,1,1,0,0,3,[55],https://icdn.lenta.ru/images/2024/01/09/02/202...,1704758160,Фото: Evelyn Hockstein / Reuters Марина Совина...,«Политически уже умер» На Украине высказались ...,Фото: Evelyn Hockstein / Reuters Марина ... Вл...,3,3396
2,1552649,https://lenta.ru/news/2024/01/09/udari/,В Киеве заявили о неспособности Украины произв...,1704756532,1704762125,1,1,0,0,3,[55],https://icdn.lenta.ru/images/2024/01/09/04/202...,1704756532,Фото: Oleksandr Ratushniak / Reuters Марина Со...,В Киеве заявили о неспособности Украины произв...,Фото: Oleksandr Ratushniak / Reuters ... произ...,3,1067
3,1552652,https://lenta.ru/news/2024/01/08/na-ukraine-za...,На Украине заявили о политической смерти Зелен...,1704756300,1704756906,1,1,0,0,3,[55],https://icdn.lenta.ru/images/2024/01/09/02/202...,1704756300,Владимир Зеленский Фото: www.imago-images.de/G...,На Украине заявили о политической смерти Зелен...,Владимир Зеленский Фото: www.imago-... Зеленск...,3,1161
4,1552650,https://lenta.ru/news/2024/01/09/zaluzhnyy/,Главком ВСУ заявил о новых атаках на военные о...,1704755700,1704769204,1,1,0,0,3,[55],https://icdn.lenta.ru/images/2024/01/09/02/202...,1704755700,Фото: Valentyn Ogirenko / Reuters Марина Совин...,Главком ВСУ заявил о новых атаках на военные о...,Фото: Valentyn Ogirenko / Reuters Марина ... в...,3,985
6,1552644,https://lenta.ru/news/2024/01/09/bolts/,Американская авиакомпания нашла незатянутые бо...,1704753360,1704753492,1,1,0,0,48,[158],https://icdn.lenta.ru/images/2024/01/09/01/202...,1704753360,Фото: NTSB / Reuters Марина Совина Специалисты...,Американская авиакомпания нашла незатянутые бо...,Фото: NTSB / Reuters Марина Совина ... болты н...,7,893
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207666,1805033,https://lenta.ru/news/2025/03/24/yurist-rasska...,Юрист рассказал о выплате от работодателей с 1...,1742776260,1742777586,1,1,0,0,4,[198],https://icdn.lenta.ru/images/2025/03/24/03/202...,1742776260,Фото: Unsplash Марина Совина Генеральный дирек...,Юрист рассказал о выплате от работодателей с 1...,Фото: Unsplash Марина Совина Генеральный ... в...,1,902
207667,1805032,https://lenta.ru/news/2025/03/24/ranenyy-rossi...,Раненый российский боец встретил удар дрона ВС...,1742775840,1742781281,1,1,0,1,1,[2],https://icdn.lenta.ru/images/2025/03/24/03/202...,1742775840,Фото: Shatokhina Natalia / Globallookpress.com...,Раненый российский боец встретил удар дрона ВС...,"Фото: Shatokhina Natalia / ... Украины (ВСУ), ...",0,953
207669,1805009,https://lenta.ru/news/2025/03/24/hayp-na-trage...,«Хайп на трагедии недопустим». Известный рэпер...,1742774640,1742800356,1,1,0,1,1,[2],https://icdn.lenta.ru/images/2025/03/23/23/202...,1742774640,Аким Апачев Кадр: Telegram-канал WarGonzo Мари...,«Хайп на трагедии недопустим». Известный рэпер...,Аким Апачев Кадр: Telegram-канал ... сил Украи...,0,2335
207670,1805030,https://lenta.ru/news/2025/03/24/veteranov-vel...,Ветеранов Великой Отечественной войны обеспеча...,1742774580,1742775600,1,1,0,0,4,[388],https://icdn.lenta.ru/images/2025/03/24/02/202...,1742774580,Фото: Unsplash Марина Совина Зампред комитета ...,Ветеранов Великой Отечественной войны обеспеча...,Фото: Unsplash Марина Совина Зампред ... в улу...,1,1029
207671,1804092,https://lenta.ru/news/2025/03/24/rossiyskiy-bu...,Российский «Булат» определит типы атакующих БПЛА,1742774463,1742774463,1,1,0,0,5,[13],https://icdn.lenta.ru/images/2025/03/21/13/202...,1742774463,Фото: Евгений Биятов / РИА Новости Иван Потапо...,Российский «Булат» определит типы атакующих БПЛА,Фото: Евгений Биятов / РИА Новости Иван ... ле...,8,1204

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import MaxAbsScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [ ]:
X = df['text']
y = df['topic']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Для преобразования текстов в числовые признаки использовался CountVectorizer (Bag of Words). Метод строит словарь уникальных слов и представляет каждый документ в виде вектора частот встречаемости слов

In [ ]:
vec = CountVectorizer(max_features=50000, ngram_range=(1, 2), min_df=3, max_df=0.9)
vec.fit(X_train)
bow = vec.transform(X_train)
bow_test = vec.transform(X_test)
print(bow.shape)

(111044, 50000)

In [ ]:
scaler = MaxAbsScaler()
bow = scaler.fit_transform(bow)
bow_test = scaler.transform(bow_test)

In [ ]:
clf = LogisticRegression(max_iter=200, random_state=42)
clf.fit(bow, y_train)

LogisticRegression(max_iter=200, random_state=42)

In [ ]:
pred = clf.predict(bow_test)
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.90      0.91      0.91      7406
           1       0.94      0.94      0.94      5153
           2       0.96      0.95      0.96      3861
           3       0.93      0.94      0.93      5394
           4       1.00      0.99      0.99      1783
           5       0.99      0.98      0.98       961
           7       0.97      0.95      0.96      1571
           8       0.96      0.94      0.95      1632

    accuracy                           0.94     27761
   macro avg       0.96      0.95      0.95     27761
weighted avg       0.94      0.94      0.94     27761

In [ ]:
from sklearn.svm import LinearSVC

In [ ]:
svc = LinearSVC(random_state=42)
svc.fit(bow, y_train)

LinearSVC(random_state=42)

In [ ]:
pred_svc = svc.predict(bow_test)
print(classification_report(y_test, pred_svc))

              precision    recall  f1-score   support

           0       0.90      0.90      0.90      7406
           1       0.95      0.94      0.94      5153
           2       0.95      0.95      0.95      3861
           3       0.92      0.94      0.93      5394
           4       0.99      0.99      0.99      1783
           5       0.98      0.97      0.98       961
           7       0.97      0.96      0.97      1571
           8       0.96      0.95      0.95      1632

    accuracy                           0.94     27761
   macro avg       0.95      0.95      0.95     27761
weighted avg       0.94      0.94      0.94     27761

In [ ]:
from sklearn.metrics import accuracy_score
print('Logistic Regression:', accuracy_score(y_test, pred))
print('LinearSVC:', accuracy_score(y_test, pred_svc))

Logistic Regression: 0.939879687331148
LinearSVC: 0.9376823601455279

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
params = {'C': [0.1, 1, 5],}

In [ ]:
grid_lr = GridSearchCV(LogisticRegression(max_iter=200, random_state=42),
    params,
    cv=3,
    scoring='accuracy',
    n_jobs=-1)

In [ ]:
grid_lr.fit(bow, y_train)
grid_lr.best_params_

{'C': 0.1}

In [ ]:
grid_lr.best_score_

np.float64(0.9421670688191424)

In [ ]:
grid_svc = GridSearchCV(LinearSVC(random_state=42),
    params,
    cv=3,
    scoring='accuracy',
    n_jobs=-1
)

In [ ]:
grid_svc.fit(bow, y_train)
grid_svc.best_params_

{'C': 0.1}

In [ ]:
grid_svc.best_score_

np.float64(0.9388620690325494)

In [ ]:
X_full = df['text']
y_full = df['topic']

In [ ]:
vec = CountVectorizer(
    max_features=50000,
    ngram_range=(1, 2),
    min_df=3,
    max_df=0.9)

In [ ]:
bow_full = vec.fit_transform(X_full)
scaler = MaxAbsScaler()
bow_full = scaler.fit_transform(bow_full)

In [ ]:
final_model = LogisticRegression(C=0.1, max_iter=200, random_state=42)

In [ ]:
final_model.fit(bow_full, y_full)

LogisticRegression(C=0.1, max_iter=200, random_state=42)

In [ ]:
test_df = pd.read_csv('/content/test_news.csv')

In [ ]:
test_df.columns

Index(['content'], dtype='object')

In [ ]:
test_bow = vec.transform(test_df['content'])

In [ ]:
test_pred = final_model.predict(test_bow)

In [ ]:
submission = pd.DataFrame({'topic': test_pred, 'index': range(len(test_pred))})

In [ ]:
submission.head()

   topic  index
0      0      0
1      1      1
2      4      2
3      0      3
4      4      4

In [ ]:
submission.to_csv('submission.csv', index=False)

ЛР показала лучший результат. Вероятно, это связано с тем, что модель хорошо работает на высокоразмерных разреженных признаках и лучше обобщает данные выборки